# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['Main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('venv/Lib/site-packages/PySide6/Qt/plugins', 'PySide6/Qt/plugins'),
        ('venv/Lib/site-packages/PySide6/Qt/bin', 'PySide6/Qt/bin'),
    ],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtWidgets',
        'PySide6.QtGui',
        'PySide6.QtOpenGL',
        'PySide6.QtPrintSupport',
        'PySide6.QtSql',
        'PySide6.QtSvg',
        'PySide6.QtTest',
        'PySide6.QtUiTools',
        'PySide6.QtWebEngine',
        'PySide6.QtWebEngineCore',
        'PySide6.QtWebEngineWidgets',
        'PySide6.QtXml',
        'docx',
        'openpyxl',
        'lxml',
        'et_xmlfile',
        'shiboken6',
        'PySide6_Addons',
        'PySide6_Essentials',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Main',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
