[tool.black]
line-length = 119
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # ...
)/
'''

[tool.flake8]
max-line-length = 119
extend-ignore = "E203,W503"
exclude = [".git", "__pycache__", "build", "dist", "venv"]

[tool.isort]
profile = "black"
line_length = 119
